x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  nitro:
    restart: "unless-stopped"
    image: ${DOCKER_REPO}:${NITRO_DOCKER_TAG}
    stop_grace_period: 5m
    volumes:
      - nitro-data:/home/user/.arbitrum
      - /etc/localtime:/etc/localtime:ro
      - ./apechain/nodeConfig.json:/config/nodeConfig.json
    <<: *logging
    entrypoint:
      - nitro
      - --conf.file=/config/nodeConfig.json
      - --parent-chain.connection.url
      - ${PARENT_RPC}
      - --execution.forwarding-target=https://apechain.calderachain.xyz/http
      - --node.feed.input.url=wss://apechain.calderachain.xyz/feed
      - --node.data-availability.rest-aggregator.urls="https://apechain.calderachain.xyz/rest-aggregator"
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT:-8547}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.rpcprefix=/
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8548}
      - --ws.origins=*
      - --ws.rpcprefix=/
      - --metrics
      - --metrics-server.addr
      - 0.0.0.0
      - --file-logging.enable=false
      - --log-level
      - ${LOG_LEVEL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-apechain}.service=${RPC_HOST:-apechain}
      - traefik.http.routers.${RPC_HOST:-apechain}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-apechain}.rule=Host(`${RPC_HOST:-apechain}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-apechain}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-apechain}lb.service=${RPC_HOST:-apechain}
      - traefik.http.routers.${RPC_HOST:-apechain}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-apechain}lb.rule=Host(`${RPC_LB:-apechain-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-apechain}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-apechain}.loadbalancer.server.port=${RPC_PORT:-8547}
      - traefik.http.routers.${WS_HOST:-apechainws}.service=${WS_HOST:-apechainws}
      - traefik.http.routers.${WS_HOST:-apechainws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-apechainws}.rule=Host(`${WS_HOST:-apechainws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-apechainws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-apechainws}lb.service=${WS_HOST:-apechainws}
      - traefik.http.routers.${WS_HOST:-apechainws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-apechainws}lb.rule=Host(`${WS_LB:-apechainws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-apechainws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-apechainws}.loadbalancer.server.port=${WS_PORT:-8548}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6070
      - metrics.network=${NETWORK}

volumes:
  nitro-data:
